name: Run WEB Tests
run-name: On Push - Web Tests Run
on: [push]

jobs:
  web-tests:
    runs-on: ubuntu-20.04
    permissions: write-all
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js 19.1
        uses: actions/setup-node@v4
        with:
          node-version: '19.1'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          npm install @playwright/test
          npx playwright install-deps
          rfbrowser init

      - name: Run RF WEB Tests
        run: |
          robot -d ./results -v HEADLESS:true \
          -v BROWSER:${{ matrix.browser }} tests

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.browser }}
          path: ./results
          if-no-files-found: ignore
          retention-days: 2

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: ./results
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: false
